"use client";

import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { Toast } from "@/components/ui/Toast";
import { type AparenciaDoSite, type LinkDoSite } from "@/lib/site/aparencia";
import { salvarConfiguracaoAction } from "../configuracoes/actions";

function CamposDeLinks({ titulo, itens, onChange }: { titulo: string; itens: LinkDoSite[]; onChange: (itens: LinkDoSite[]) => void }) {
  return <section className="flex flex-col gap-3 rounded-lg border border-sand p-4"><h2 className="font-display text-lg text-ink">{titulo}</h2>{itens.map((item, i) => <div key={i} className="grid gap-2 sm:grid-cols-2"><input aria-label={`Nome ${i + 1}`} value={item.label} onChange={(e) => onChange(itens.map((x, n) => n === i ? { ...x, label: e.target.value } : x))} className="min-h-toque rounded-md border border-sand px-3" placeholder="Nome" /><input aria-label={`Link ${i + 1}`} value={item.href} onChange={(e) => onChange(itens.map((x, n) => n === i ? { ...x, href: e.target.value } : x))} className="min-h-toque rounded-md border border-sand px-3" placeholder="/pagina" /></div>)}</section>;
}

export function SiteManager({ initial }: { initial: AparenciaDoSite }) {
  const [site, setSite] = useState(initial); const [salvando, setSalvando] = useState(false); const [mensagem, setMensagem] = useState<string | null>(null); const [erro, setErro] = useState(false);
  const campo = (key: keyof Pick<AparenciaDoSite, "brandName" | "logoUrl" | "seoTitle" | "seoDescription" | "instagramUrl">, label: string, grande = false) => <label className="flex flex-col gap-1 text-sm font-medium text-ink">{label}{grande ? <textarea value={site[key] as string} onChange={(e) => setSite({ ...site, [key]: e.target.value })} rows={3} className="rounded-md border border-sand px-3 py-2 font-normal" /> : <input value={site[key] as string} onChange={(e) => setSite({ ...site, [key]: e.target.value })} className="min-h-toque rounded-md border border-sand px-3 font-normal" />}</label>;
  async function salvar() { setSalvando(true); setMensagem(null); const r = await salvarConfiguracaoAction({ key: "site_appearance", valueJson: JSON.stringify(site) }); setSalvando(false); setErro("error" in r); setMensagem("error" in r ? r.error : "Alterações salvas e publicadas no site."); }
  const [largura, setLargura] = useState<"desktop" | "tablet" | "celular">("desktop");
  const moldura = largura === "desktop" ? "w-full" : largura === "tablet" ? "w-[768px] max-w-full" : "w-[390px] max-w-full";
  return <div className="flex flex-col gap-5">{mensagem ? <Toast message={mensagem} variant={erro ? "error" : "success"} onClose={() => setMensagem(null)} /> : null}<section className="rounded-lg border border-sand p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-lg text-ink">Visualizar como comprador</h2><p className="text-sm text-ink/70">Esta é a própria página pública, sem cópia dentro do ADMIN. Para trocar uma mídia que você vê abaixo, use os atalhos de edição.</p></div><div className="flex flex-wrap gap-2">{(["desktop","tablet","celular"] as const).map((v) => <Button key={v} type="button" size="sm" variant={largura === v ? "primary" : "ghost"} onClick={() => setLargura(v)}>{v}</Button>)}<a href="/admin/textos" className="inline-flex min-h-toque items-center rounded-md border border-sand px-3 text-sm text-ink">Editar fotos</a><a href="/admin/videos" className="inline-flex min-h-toque items-center rounded-md border border-sand px-3 text-sm text-ink">Editar vídeos</a></div></div><div className="overflow-auto bg-sand p-3"><iframe title="Página pública da Reverá" src="/" className={`mx-auto h-[680px] bg-paper ${moldura}`} /></div></section><section className="grid gap-4 rounded-lg border border-sand p-4 sm:grid-cols-2">{campo("brandName", "Nome da marca")}{campo("logoUrl", "URL da logo (use a Biblioteca para enviar a imagem)")}{campo("seoTitle", "Título para Google e compartilhamentos", true)}{campo("seoDescription", "Descrição para Google e compartilhamentos", true)}{campo("instagramUrl", "Link do Instagram")}</section><CamposDeLinks titulo="Menu principal" itens={site.menuPrincipal} onChange={(menuPrincipal) => setSite({ ...site, menuPrincipal })} /><CamposDeLinks titulo="Menu “Conheça”" itens={site.menuConheca} onChange={(menuConheca) => setSite({ ...site, menuConheca })} /><CamposDeLinks titulo="Link para profissionais" itens={[site.linkProfissionais]} onChange={(links) => setSite({ ...site, linkProfissionais: links[0]! })} /><div><Button type="button" onClick={salvar} disabled={salvando}>{salvando ? "Salvando..." : "Salvar alterações do site"}</Button></div></div>;
}
